project:
  title: "IntroToRcensusPkg"
  output-dir: output
format:
  html:
    fontsize: 1.4rem
    page-layout: full
    theme:
      light: cosmo
      dark: darkly
    css: style.css
    toc: true
    other-links:
      - text: RcensusPkg
        href: https://github.com/deandevl/RcensusPkg
      - text: deandevl
        href: https://github.com/deandevl
    code-links:
      - text: source
        icon: github
        href: "https://github.com/deandevl/IntroToRcensusPkg"

number-sections: true
date: last-modified
author: Rick Dean
